# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Version
mod_version=2.1.00-pre1

# Mod
mod_id=aether_redux
mod_name=The Aether: Redux
mod_license=All Rights Reserved
mod_authors=Zepalesque
mod_tracker=https://github.com/Zepalesque/The-Aether-Redux/issues
mod_url=https://modrinth.com/mod/the-aether-redux
mod_credits=The Aether Team, Aerod, BrianIsBro, Emile van Kreiken, 345boneshoss, RazorDevs, unroman, Parallel113, IcyCrystal, ModdingLegacy, Builderdog841, Jonathing, LlamaLad7, Shimmer.shine/Wurlette
mod_description=\nThe Aether: Redux is an expansive addon mod for the well-known Aether mod, adding a wide variety of new content ranging from several new biomes to an overhaul to the mod's first dungeon. There are a variety of other new features as well! \n\nA whole lot of new mob models have also been implemented, which are all configurable as well, so you can choose between Redux's upgraded versions and the originals if you prefer them. \n\nYou can also configure Redux's built-in asset overrides resource pack, using the new in-game config system created specifically for this, so you can change the appearance of various parts of the mod to your hearts content! \n\nSpeaking of configuration, the mod also has a ton of configuration options, so check those out, as you could very well prefer certain options over others.

# Dependencies
moddevgradle_version=2.0.42-beta
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)

neo_version=21.1.72
neo_version_range=[21.1.72,)

loader_version_range=[4,)
mixin_version=0.8.5
mappings_mc_ver=1.21
mappings=2024.06.23

# Required Dependencies
zenith_version=1.3.03
unity_version=0.1.16
aether_version=1.5.4
nitrogen_version=1.1.22
cumulus_version=2.0.0

accessories_version=1.1.0-beta.16


aeroblender_version=5911923
terrablender_version=1.21.1-4.1.0.5
terrablender_version_range=[1.21.1-4.1.0.0, 1.21.1-4.1.1.0)

# Other Dependencies
appleskin_version=5586600
cyanide_version=5782674
jade_version=5813144
spark_version=5759671
configured_version=5873783